POST http://localhost:3001/api/persons/ HTTP/1.1
content-Type: application/json

{
    "name": "Post Rest", 
    "number": "44337998"
}

###

GET http://localhost:3001/api/persons/ HTTP/1.1
content-Type: application/json